version: '3'

networks:
  front:
  back:
    internal: true

services:
  db:
    image: postgres:10-alpine
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=postgres
    networks:
      - back
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    image: gitea/gitea:latest
    restart: always
    container_name: gitea
    networks:
      - front
      - back
    ports:
      - "80:3000"
      - "2022:22"
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
