version: '3'
services:

  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=postgres
    networks:
      - gitea_back
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    image: gitea/gitea:1.5
    restart: always
    networks:
      - gitea_front
      - gitea_back
    ports:
      - "3005:3000"
      - "3020:22"
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./gitea:/data

networks:
  gitea_front:
  gitea_back:
    internal: true
